inherited fform_modelo_cadastro: Tfform_modelo_cadastro
  Caption = 'fform_modelo_cadastro'
  ClientHeight = 433
  ClientWidth = 862
  Position = poDesktopCenter
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  ExplicitWidth = 878
  ExplicitHeight = 472
  PixelsPerInch = 96
  TextHeight = 13
  inherited Panel1: TPanel
    Height = 433
    ExplicitHeight = 433
  end
  inherited Panel2: TPanel
    Width = 798
    Height = 433
    ExplicitWidth = 798
    ExplicitHeight = 433
    object Panel3: TPanel
      Left = 0
      Top = 382
      Width = 798
      Height = 51
      Align = alBottom
      BevelOuter = bvNone
      TabOrder = 0
      object Bevel1: TBevel
        Left = 0
        Top = 0
        Width = 798
        Height = 2
        Align = alTop
        ExplicitLeft = 1
        ExplicitTop = 1
        ExplicitWidth = 649
      end
      object bFechar: TButton
        AlignWithMargins = True
        Left = 698
        Top = 8
        Width = 95
        Height = 37
        Margins.Top = 6
        Margins.Right = 5
        Margins.Bottom = 6
        Align = alRight
        Caption = 'Fechar'
        TabOrder = 0
        OnClick = bFecharClick
      end
      object bExcluir: TButton
        AlignWithMargins = True
        Left = 599
        Top = 8
        Width = 95
        Height = 37
        Margins.Top = 6
        Margins.Right = 1
        Margins.Bottom = 6
        Align = alRight
        Caption = 'Excluir'
        TabOrder = 1
        OnClick = bExcluirClick
      end
      object bProximo: TButton
        Tag = 3
        AlignWithMargins = True
        Left = 203
        Top = 8
        Width = 95
        Height = 37
        Margins.Top = 6
        Margins.Right = 1
        Margins.Bottom = 6
        Align = alRight
        Caption = 'Pr'#243'ximo'
        TabOrder = 2
        OnClick = bPrimeiroClick
      end
      object bUltimo: TButton
        Tag = 4
        AlignWithMargins = True
        Left = 302
        Top = 8
        Width = 95
        Height = 37
        Margins.Top = 6
        Margins.Right = 1
        Margins.Bottom = 6
        Align = alRight
        Caption = #218'ltimo'
        TabOrder = 3
        OnClick = bPrimeiroClick
      end
      object bNovo: TButton
        AlignWithMargins = True
        Left = 401
        Top = 8
        Width = 95
        Height = 37
        Margins.Top = 6
        Margins.Right = 1
        Margins.Bottom = 6
        Align = alRight
        Caption = 'Novo'
        TabOrder = 4
        OnClick = bNovoClick
      end
      object bGravar: TButton
        AlignWithMargins = True
        Left = 500
        Top = 8
        Width = 95
        Height = 37
        Margins.Top = 6
        Margins.Right = 1
        Margins.Bottom = 6
        Align = alRight
        Caption = 'Gravar'
        TabOrder = 5
        OnClick = bGravarClick
      end
      object bAnterior: TButton
        Tag = 2
        AlignWithMargins = True
        Left = 104
        Top = 8
        Width = 95
        Height = 37
        Margins.Top = 6
        Margins.Right = 1
        Margins.Bottom = 6
        Align = alRight
        Caption = 'Anterior'
        TabOrder = 6
        OnClick = bPrimeiroClick
      end
      object bPrimeiro: TButton
        Tag = 1
        AlignWithMargins = True
        Left = 5
        Top = 8
        Width = 95
        Height = 37
        Margins.Top = 6
        Margins.Right = 1
        Margins.Bottom = 6
        Align = alRight
        Caption = 'Primeiro'
        TabOrder = 7
        OnClick = bPrimeiroClick
      end
    end
  end
end
